### ISSUE TITLE
Unused second iteration

### ISSUE THREAD

**Issue by hadiidbouk** [neXenio/BLE-Indoor-Positioning#119]
In this method, you are collecting all the advertising packets that should be removed, then you use the r`emoveAll()` method to remove them all.
Why not change this :  `advertisingPackets.removeAll(removableAdvertisingPackets);`
to this : `advertisingPackets = usedBeacons;`

Instead of collecting the advertising packets that should be removed, collect the advertising packets that should NOT be removed.

In this way, you will avoid using another loop with the `removeAll()` method.
```
 public void trimAdvertisingPackets() {
        synchronized (advertisingPackets) {
            if (!hasAnyAdvertisingPacket()) {
                return;
            }
            List<P> removableAdvertisingPackets = new ArrayList<>();
            AdvertisingPacket latestAdvertisingPacket = getLatestAdvertisingPacket();
            long minimumPacketTimestamp = System.currentTimeMillis() - MAXIMUM_PACKET_AGE;
            for (P advertisingPacket : advertisingPackets) {
                if (advertisingPacket == latestAdvertisingPacket) {
                    // don't remove the latest packet
                    continue;
                }
                if (advertisingPacket.getTimestamp() < minimumPacketTimestamp) {
                    // mark old packets as removable
                    removableAdvertisingPackets.add(advertisingPacket);
                }
            }

            advertisingPackets.removeAll(removableAdvertisingPackets);
        }
    }
```

**Comment by marvinmirtschin** [comment]
We can't set our `advertisingPackets` as they are defined final to be synchronised. 
Therefore we can either find the packets we want, clear our `advertisingPackets` and add all valid packets or we can find the ones we don't want and remove them.

As `trimAdvertisingPackets` is called for every `addAdvertisingPacket` it is more favorable to use our way as the resulting search list will be significantly smaller for growing 'MAXIMUM_PACKET_AGE' and many high frequently reporting beacons.
