### ISSUE TITLE
What's the function means under TrilaterationFunction.java

### ISSUE THREAD

**Issue by mrcrow** [neXenio/BLE-Indoor-Positioning#161]
```
public Pair<RealVector, RealMatrix> value(RealVector point)
```

I notice that the function contains two parts, one part is sort of sum and another is make Jacobian matrix for input point. 

I don't really understand what does the sum means, also this function could be separated into two functions and will works too and don't needs to make a pair at all

**Comment by Steppschuh** [comment]
The `TrilaterationFunction` class is part of the [Trilateration library](https://github.com/lemmingapex/trilateration) provided by @lemmingapex, I would encourage you to ask the question in that repo instead.

As of my understanding, the values and their derivatives directly relate to each other. The calculation could be separated into multiple methods to avoid the `Pair` instantiation, however I doubt that this would have any measurable performance impact. There's also no usage of this method where only the `RealVector` or `RealMatrix` would be required.
