### ISSUE TITLE
How to setup the BeaconLocationProvider

### ISSUE THREAD

**Issue by ahumanman** [neXenio/BLE-Indoor-Positioning#166]
how do i input my beacons geo coordinates in code. its mentioned that i should use BeaconLocationProvider that could read from the beacons advertising data but how does the library read that data from the beacon and know and distinguish if what its reading is the longitude or latitude. sorry for the basic question but im pretty to new to beacon development and android.

**Comment by Steppschuh** [comment]
Please have a look at #80 and #144 

In the sample app, there's an `IBeaconLocationProvider` in [BluetoothClient](https://github.com/neXenio/BLE-Indoor-Positioning/blob/0ce40a7db42775dc2683cd616280dac443bd4168/app/src/main/java/com/nexenio/bleindoorpositioningdemo/bluetooth/BluetoothClient.java#L136) providing hardcoded geo coordinates. You can implement something different depending on your use-case, e.g. fetching the geo coordinates from an API instead.
