### ISSUE TITLE
Can the application support beacon simulators?

### ISSUE THREAD

**Issue by jasirjasir** [neXenio/BLE-Indoor-Positioning#167]

**Comment by Steppschuh** [comment]
The app / library will work with every advertising frame, as long as the advertised data matches the beacon specification.

You can see / adjust the performed checks in the `meetsSpecification` method (e.g. in [IBeaconAdvertisingPacket](https://github.com/neXenio/BLE-Indoor-Positioning/blob/master/BLE%20Indoor%20Positioning/src/main/java/com/nexenio/bleindoorpositioning/ble/advertising/IBeaconAdvertisingPacket.java#L70)).

I'd say it depends on the beacon simulator application if they manage to advertise valid iBeacon or  Eddistone frames. A good application to inspect advertising data is [nRF Connect](https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Connect-for-mobile).
