### ISSUE TITLE
How to make the application to support all the beacons?

### ISSUE THREAD

**Issue by jasirjasir** [neXenio/BLE-Indoor-Positioning#169]
I know there is a beacon filter in your application.How to disable it to use for accepting all the ibeacons and eddystone .

**Comment by marvinmirtschin** [comment]
The [BeaconViewFragment](https://github.com/neXenio/BLE-Indoor-Positioning/blob/master/app/src/main/java/com/nexenio/bleindoorpositioningdemo/ui/beaconview/BeaconViewFragment.java) holds an IBeaconFilter `uuidFilter`. You can either remove it from being added in the `onAttach` method or call `uuidFilter.setMatchProximityUuid(false)`.
