### ISSUE TITLE
How to set Location data to beacon?

### ISSUE THREAD

**Issue by jasirjasir** [neXenio/BLE-Indoor-Positioning#171]
How do we set location data  (latitude,longitude, altitude) to the beacons. Can we perform localization without setting Geo  locations?**example**: If i want to perform indoor navigation inside a hospital where  Geo location data is not much accurate inside the rooms . I only have  a correct scaled floor plan. Can you suggest me how to implement this scenario?

**Comment by Steppschuh** [comment]
See #166
