### ISSUE TITLE
Improving Beacon distance estimation

### ISSUE THREAD

**Issue by jasirjasir** [neXenio/BLE-Indoor-Positioning#179]
How to improve distance estimation using RSSI. The distance estimated from `beacon.getDistance()` method '' is varying with different phone orientation.Also, I am facing a huge jumping nature for the estimated position while moving . Any help will be grateful.

**Comment by Steppschuh** [comment]
This is what you should expect. Distance estimation using RSSI values is not very accurate by nature. Certainly things could still be improved though, check out #127 for instance.
