### ISSUE TITLE
Demo App of indoor navigation using BLE beacons

### ISSUE THREAD

**Issue by Dreyar512** [neXenio/BLE-Indoor-Positioning#181]
Hello , 
It is possible to have just a demo app and guide about indoor navigation using BLE Beacons with the use of multilateration.
I did have a look at your project and the sample app as well , but I am not really understanding the navigation part as there is too much of code.

It would be cool if you could help.

Thanks

**Comment by Steppschuh** [comment]
This library the demo app has no component for navigation. You can use it to get the current device location based on Bluetooth signals, but you'd have to add your own wayfinding for navigation.
