### ISSUE TITLE
Able to show chart but blank on map/radar

### ISSUE THREAD

**Issue by hifnii** [neXenio/BLE-Indoor-Positioning#183]
Hello, 

Was exploring this GitHub code and wonder how I could install it properly. Manage to display iBeacon on the chart but having trouble trying to figure out why I could not load both map & radar. I've already change the lat & long, import map.

Can I check with you if I need to add some code in BeaconManager? I've already found my beacon macAddress, rssi value but unsure how to import it to BeaconManager. Sorry for this basic question, I'm new to Java Language & hope I could get guide from you.

**Comment by Steppschuh** [comment]
Hey,
make sure that you also have a valid `LocationProvider` set for your beacons. Please refer to #144 for details.
