### ISSUE TITLE
Unable to plot points

### ISSUE THREAD

**Issue by ghost** [neXenio/BLE-Indoor-Positioning#84]
I am not able to get locations.

Only Getting the following values :
AndroidLocationProvider: Received location result with 1 locations
    Last known location set to : Latitude: 30.722795 Longitude: 76.7677966

**Comment by parvinder06** [comment]
No

**Comment by Steppschuh** [comment]
Please try to report some more detailed issues. We have no idea what you are trying to accomplish, what exactly is causing issues and how you tried to solve them.

`SensorManager` could cause issues if your android device has no accelerometer or magnetic field sensor (or if you blocked access to the device sensors).

**Comment by parvinder06** [comment]
Till now i have just compiled this code and got the following result:
![screenshot_20180611-143706](https://user-images.githubusercontent.com/38680063/41222872-d7967210-6d85-11e8-9fdb-f64ed36e46cc.png)
![screenshot_20180611-143710](https://user-images.githubusercontent.com/38680063/41222873-d7ddf626-6d85-11e8-9a89-f3cca2349b58.png)
![screenshot_20180611-143715](https://user-images.githubusercontent.com/38680063/41222874-d823662a-6d85-11e8-927a-7daac40caf19.png)

**Comment by hadiidbouk** [comment]
I get this bug once when i set the Location provider as an iBeacon and the bluetooth scanner detect and Eddystone beacon.

`Java.lang.ClassCastException: com.nexenio.bleindoorpositioning.ble.beacon.Eddystone cannot be cast to com.nexenio.bleindoorpositioning.ble.beacon.IBeacon`

**Comment by Steppschuh** [comment]
@parvinder06 what you are seeing is the expected result, if you have not setup your own beacons with their respective location providers yet.

I guess you haven't calculated the geo-coordinates of your beacons yet. Please follow [these steps](https://github.com/neXenio/BLE-Indoor-Positioning/wiki/Calculating-Geo-Coordinates-of-Beacons) in order to do so.

**Comment by Steppschuh** [comment]
@hadiidbouk some beacons are capable of advertising multiple frames simultaneously (e.g. iBeacon and Eddystone frames). Are stacktrace would be nice if you think that this is an issue with the library.

**Comment by hadiidbouk** [comment]
Sure i will create an issue later

**Comment by parvinder06** [comment]
Can you please provide your .apk file ?

**Comment by hadiidbouk** [comment]
@parvinder06  I am just running the [sample application](https://github.com/neXenio/BLE-Indoor-Positioning/tree/master/app) now

**Comment by parvinder06** [comment]
@hadiidbouk can you please attach .apk file? 
Actually, I want to relate it with my .apk file.

**Comment by Steppschuh** [comment]
@parvinder06 this is a debug build APK from the current dev ([e6c387d](https://github.com/neXenio/BLE-Indoor-Positioning/tree/e6c387daa0592926ce23fa1df46c70553649f0b4)): 
[ble-indoor-positioning-dev-e6c387d.apk.zip](https://github.com/neXenio/BLE-Indoor-Positioning/files/2092978/ble-indoor-positioning-dev-e6c387d.apk.zip)

**Comment by parvinder06** [comment]
@Steppschuh   I am sorry but the APK you have sent is not getting installed as it is in debug build. You have to make it signed first.

**Comment by Steppschuh** [comment]
There's absolutely no reason to sign the APK. You can easily checkout the repo and build (and sign) the APK yourself.

**Comment by Steppschuh** [comment]
Closing this because I don't see any issues here. Feel free to re-open.
