### ISSUE TITLE
registerLocationListener & unregisterLocationListener method parameters convention

### ISSUE THREAD

**Issue by hadiidbouk** [neXenio/BLE-Indoor-Positioning#93]
Hello,

The registerLocationListener (unregisterLocationListener) method in `AndroidLocationProvider` are not nullable

`registerLocationListener(@NonNull LocationListener locationListener)`

But the same method in the `IndoorPositioning` (Which should be named IndoorPositioningProvider - i guess) are nullable.

`registerLocationListener(LocationListener locationListener)`

Can we follow the same convention in both methods ?

**Comment by Steppschuh** [comment]
That's true, but won't change anytime soon. It's because the `@NonNull` annotation is part of `android.support.annotation` and thus not available in the Java core library.

**Comment by hadiidbouk** [comment]
But isn't the Java 8 contains a `@NonNull` annotation ?

Check [this](https://blogs.oracle.com/java-platform-group/java-8s-new-type-annotations)

**Comment by Steppschuh** [comment]
Thanks for the heads up. We'll see if and how we can combine these annotations.
