### ISSUE TITLE
App crash in updateLocation method

### ISSUE THREAD

**Issue by hadiidbouk** [neXenio/BLE-Indoor-Positioning#94]
Hello,

I found that the App crash when the number of my beacons is 4 in `updateLocation()` method inside the `IndoorPositioning` class

`No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)`

1 - 
<img width="946" alt="screen shot 2018-06-20 at 10 26 23 am" src="https://user-images.githubusercontent.com/19314956/41643802-f39f0af8-7474-11e8-8a6a-472e5eb20df1.png">

2 -
<img width="663" alt="screen shot 2018-06-20 at 10 26 55 am" src="https://user-images.githubusercontent.com/19314956/41643809-fa71ba9c-7474-11e8-9123-51a11fc59a72.png">

3 -
<img width="1027" alt="screen shot 2018-06-20 at 10 27 31 am" src="https://user-images.githubusercontent.com/19314956/41643817-0144cc38-7475-11e8-9c21-309e6b1cb67c.png">

Here is the 4 beacons from `usableBeacons` ArrayList : 

1 - 
<img width="409" alt="screen shot 2018-06-20 at 10 34 17 am" src="https://user-images.githubusercontent.com/19314956/41644053-b66f0c72-7475-11e8-8be2-48d1691d989e.png">

2 - 
<img width="392" alt="screen shot 2018-06-20 at 10 34 36 am" src="https://user-images.githubusercontent.com/19314956/41644058-bb9ce106-7475-11e8-874f-220e14d3efd4.png">

3 -
<img width="376" alt="screen shot 2018-06-20 at 10 34 45 am" src="https://user-images.githubusercontent.com/19314956/41644070-c2332c28-7475-11e8-98fe-86144a37765b.png">

4 -
<img width="363" alt="screen shot 2018-06-20 at 10 34 54 am" src="https://user-images.githubusercontent.com/19314956/41644083-ca9f20ce-7475-11e8-9f6f-36bf405d91e1.png">
 

PS: I am working with the dev branch 
`'implementation 'com.github.neXenio:BLE-Indoor-Positioning:dev-SNAPSHOT'`

**Comment by hadiidbouk** [comment]
After searching a little bit i found that it's not recommended to use ArrayList#sort if the app targeting Api Level > 25.

Instead we should use `Collections.sort(list, comparator)`.

```
Implementation Note:
This implementation defers to the List.sort(Comparator) method using the specified list and a null comparator. Do not call this method from List.sort() since that can lead to infinite recursion. Apps targeting APIs <= 25 observe backwards compatibility behavior where this method was implemented on top of List.toArray(), ListIterator.next() and ListIterator.set(Object). 
```

check [this](https://developer.android.com/reference/java/util/Collections#sort(java.util.List%3CT%3E)) and [this](https://developer.android.com/reference/java/util/ArrayList#sort(java.util.Comparator%3C?%20super%20E%3E)).

I sent a [PR](https://github.com/neXenio/BLE-Indoor-Positioning/pull/95) to fix this bug.

**Comment by Steppschuh** [comment]
I find it strange that we didn't ran into this issue, as we're also targeting API level 26 and have > 3 beacons in range all the time. Anyway, glad you figured out that using `Collections.sort(list, comparator)` fixed this issue for you.
